name: Build Kernel Ginkgo (KSU)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ksun

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison build-essential ccache curl flex git \
          libssl-dev libncurses-dev lzop python-is-python3 \
          unzip zip zstd

    - name: Setup Proton Clang
      run: |
        wget https://github.com/kdrag0n/proton-clang/releases/download/20210130/proton-clang-20210130.tar.zst
        tar -I zstd -xf proton-clang-20210130.tar.zst
        echo "$(pwd)/proton-clang/bin" >> $GITHUB_PATH

    - name: Export build variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "LD=ld.lld" >> $GITHUB_ENV
        echo "AR=llvm-ar" >> $GITHUB_ENV
        echo "NM=llvm-nm" >> $GITHUB_ENV
        echo "OBJCOPY=llvm-objcopy" >> $GITHUB_ENV
        echo "OBJDUMP=llvm-objdump" >> $GITHUB_ENV
        echo "STRIP=llvm-strip" >> $GITHUB_ENV

    - name: Kernel defconfig
      run: |
        make vendor/ginkgo_defconfig

    - name: Build kernel
      run: |
        make -j$(nproc)

    - name: Upload Image.gz
      uses: actions/upload-artifact@v4
      with:
        name: kernel-ginkgo-ksun
        path: |
          out/arch/arm64/boot/Image.gz
          out/arch/arm64/boot/Image.gz-dtb
