name: Build Kernel Ginkgo (KSU)

on:
  workflow_dispatch:
  push:
    branches:
      - ksun

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-20.04

    steps:
    # ===============================
    # Checkout source
    # ===============================
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # ===============================
    # Install dependencies
    # ===============================
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison build-essential ccache curl flex \
          git gnupg gperf libncurses-dev \
          libssl-dev libelf-dev lzop \
          python3 python-is-python3 \
          zip unzip zstd

    # ===============================
    # Setup AOSP Clang (STABLE)
    # ===============================
    - name: Setup AOSP Clang
      run: |
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 prebuilts-clang
        echo "CLANG_PATH=$PWD/prebuilts-clang/clang-r487747c/bin" >> $GITHUB_ENV
        echo "$PWD/prebuilts-clang/clang-r487747c/bin" >> $GITHUB_PATH

    # ===============================
    # Export build variables
    # ===============================
    - name: Export build variables
      run: |
        echo "ARCH=arm64" >> $GITHU
